const SEARCH_FILMES_RESULT = {
  "page": 1,
  "total_results": 49,
  "total_pages": 3,
  "results": [{
      "vote_count": 14100,
      "id": 603,
      "video": false,
      "vote_average": 8.1,
      "title": "The Matrix",
      "popularity": 30.063,
      "poster_path": "/hEpWvX6Bp79eLxY1kX5ZZJcme5U.jpg",
      "original_language": "en",
      "original_title": "The Matrix",
      "genre_ids": [
        28,
        878
      ],
      "backdrop_path": "/icmmSD4vTTDKOq2vvdulafOGw93.jpg",
      "adult": false,
      "overview": "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
      "release_date": "1999-03-30"
    },
    {
      "vote_count": 5567,
      "id": 604,
      "video": false,
      "vote_average": 6.9,
      "title": "The Matrix Reloaded",
      "popularity": 21.014,
      "poster_path": "/ezIurBz2fdUc68d98Fp9dRf5ihv.jpg",
      "original_language": "en",
      "original_title": "The Matrix Reloaded",
      "genre_ids": [
        12,
        28,
        53,
        878
      ],
      "backdrop_path": "/Fp3piEuHXxKnPBO5R0Wj4wjZHg.jpg",
      "adult": false,
      "overview": "Six months after the events depicted in The Matrix, Neo has proved to be a good omen for the free humans, as more and more humans are being freed from the matrix and brought to Zion, the one and only stronghold of the Resistance.  Neo himself has discovered his superpowers including super speed, ability to see the codes of the things inside the matrix and a certain degree of pre-cognition. But a nasty piece of news hits the human resistance: 250,000 machine sentinels are digging to Zion and would reach them in 72 hours. As Zion prepares for the ultimate war, Neo, Morpheus and Trinity are advised by the Oracle to find the Keymaker who would help them reach the Source.  Meanwhile Neo's recurrent dreams depicting Trinity's death have got him worried and as if it was not enough, Agent Smith has somehow escaped deletion, has become more powerful than before and has fixed Neo as his next target.",
      "release_date": "2003-05-15"
    },
    {
      "vote_count": 5004,
      "id": 605,
      "video": false,
      "vote_average": 6.6,
      "title": "The Matrix Revolutions",
      "popularity": 18.799,
      "poster_path": "/2aJvwc4zXqtVUDbEu62e14J0mhe.jpg",
      "original_language": "en",
      "original_title": "The Matrix Revolutions",
      "genre_ids": [
        12,
        28,
        53,
        878
      ],
      "backdrop_path": "/pdVHUsb2eEz9ALNTr6wfRJe5xVa.jpg",
      "adult": false,
      "overview": "The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.",
      "release_date": "2003-11-05"
    },
    {
      "vote_count": 98,
      "id": 14543,
      "video": false,
      "vote_average": 6.8,
      "title": "The Matrix Revisited",
      "popularity": 5.122,
      "poster_path": "/kR4xt6eVdTS1agmUiL4RHXEYkDs.jpg",
      "original_language": "en",
      "original_title": "The Matrix Revisited",
      "genre_ids": [
        99
      ],
      "backdrop_path": "/lBdXACywnLwKUZmZkZ87djDQBeV.jpg",
      "adult": false,
      "overview": "The film goes behind the scenes of the 1999 sci-fi movie The Matrix.",
      "release_date": "2001-11-19"
    },
    {
      "vote_count": 20,
      "id": 221495,
      "video": false,
      "vote_average": 6.5,
      "title": "The Matrix Recalibrated",
      "popularity": 2.005,
      "poster_path": "/sVP2PpetwT8Qg82M48tYA0ILije.jpg",
      "original_language": "en",
      "original_title": "The Matrix Recalibrated",
      "genre_ids": [
        99,
        878
      ],
      "backdrop_path": null,
      "adult": false,
      "overview": "The making of Matrix Revolutions, The (2003) is briefly touched on here in this documentary. Interviews with various cast and crew members inform us how they were affected by the deaths of Gloria Foster and Aaliyah, and also delve into the making of the visual effects that takes up a lot of screen time. Written by Rhyl Donnelly",
      "release_date": "2004-04-06"
    },
    {
      "vote_count": 0,
      "id": 373223,
      "video": false,
      "vote_average": 0,
      "title": "Matrix",
      "popularity": 0.6,
      "poster_path": "/vTHCcWv6y2ZJHj0uEcBFmpnhi9r.jpg",
      "original_language": "en",
      "original_title": "Matrix",
      "genre_ids": [],
      "backdrop_path": null,
      "adult": false,
      "overview": "Abstract art film made for gallery exhibition.",
      "release_date": "1973-01-01"
    },
    {
      "vote_count": 0,
      "id": 411948,
      "video": false,
      "vote_average": 0,
      "title": "Matrix",
      "popularity": 0.6,
      "poster_path": "/cseRq8R9RGN66SNUgcD7RJAxBI7.jpg",
      "original_language": "en",
      "original_title": "Matrix",
      "genre_ids": [],
      "backdrop_path": null,
      "adult": false,
      "overview": "John Whitney, Sr. (April 8, 1917 – September 22, 1995) was an American animator, composer and inventor, widely considered to be one of the fathers of computer animation.",
      "release_date": "1971-05-18"
    },
    {
      "vote_count": 0,
      "id": 555879,
      "video": false,
      "vote_average": 0,
      "title": "Matrix",
      "popularity": 0.6,
      "poster_path": "/AfFD10ZqEx2vkxM2yvRZkybsGB7.jpg",
      "original_language": "en",
      "original_title": "Matrix",
      "genre_ids": [],
      "backdrop_path": null,
      "adult": false,
      "overview": "The film is composed of receding planes in a landscape: a back garden and the houses beyond. The wooden lattice fence, visible in the image, marks the border between enclosed and open, private and public space, and forms both a fulcrum for the work and a formal grid by which the shots are framed and organised.",
      "release_date": "1998-12-31"
    },
    {
      "vote_count": 4,
      "id": 51767,
      "video": false,
      "vote_average": 5.4,
      "title": "Sexual Matrix",
      "popularity": 1.118,
      "poster_path": "/leZ7bOP0wSvtweHHYwDze4m7oMr.jpg",
      "original_language": "en",
      "original_title": "Sexual Matrix",
      "genre_ids": [
        878
      ],
      "backdrop_path": "/gIWzjbtd2XYPnu1zttI8fzG93cU.jpg",
      "adult": false,
      "overview": "\"Sexual Matrix\" is about a matrix that is sexual. A horny professor decides to ask his students all about their sexual fantasies. Of course he does. So while they're describing their wildest dreams, he plugs them into his matrix machine and it lets them live out their fantasies. It seems so real! Mia Zottoli shows up to assist the professor in his quest to know what turns the whole campus on",
      "release_date": "2000-04-01"
    },
    {
      "vote_count": 20,
      "id": 33322,
      "video": false,
      "vote_average": 6.7,
      "title": "Armitage III: Poly Matrix",
      "popularity": 1.788,
      "poster_path": "/7sUCRdjGe7VggDCGIHywfguYdAK.jpg",
      "original_language": "ja",
      "original_title": "アミテージ・ザ・サード POLY-MATRIX",
      "genre_ids": [
        16,
        878,
        53
      ],
      "backdrop_path": "/zY8YvEUXwvsQFcQmzqyVQA5wq5j.jpg",
      "adult": false,
      "overview": "Ross Sylibus is assigned to a police unit on a Martian colony, to find that women are being murdered by a psychotic named D'anclaude. He is assigned a very unorthodox partner named Naomi Armitage, who seems to have links to the victims. To stir things up more, every victim is found to be an illegally made third-generation android.",
      "release_date": "1996-06-25"
    },
    {
      "vote_count": 0,
      "id": 259464,
      "video": false,
      "vote_average": 0,
      "title": "V-World Matrix",
      "popularity": 1.091,
      "poster_path": "/9jdGgfQnMQ1B3qaYdtx2pMMcixV.jpg",
      "original_language": "en",
      "original_title": "V-World Matrix",
      "genre_ids": [
        878,
        14,
        27
      ],
      "backdrop_path": null,
      "adult": false,
      "overview": "Two friends take a cyber vacation to experience a world where they can act out their virtual fantasies! They soon realize they've entered a virtual free-for-all. Forbidden fantasies and desires suddenly appear in the form of the even deadlier \"dark woman\". All the players now end up in a cyber battle for their lives, and sanity, against a beautiful virtual hunter who has one killer fixation - winning the deadly game they started!",
      "release_date": "1999-01-01"
    },
    {
      "vote_count": 20,
      "id": 21769,
      "video": false,
      "vote_average": 6.4,
      "title": "Armitage: Dual Matrix",
      "popularity": 1.383,
      "poster_path": "/oKP0UiMxSGT9J7wpPZnFwW4z2YY.jpg",
      "original_language": "ja",
      "original_title": "アミテージ・ザ・サード DUAL-MATRIX",
      "genre_ids": [
        53,
        28,
        16,
        878,
        12
      ],
      "backdrop_path": "/95etXXpKuKsYFy1Cpa0ZXSTqBGk.jpg",
      "adult": false,
      "overview": "Naomi Armitage and Ross Sylibus have changed their names and live with their daughter Yoko as a happy and normal family on Mars — until an android riot breaks out at an anti-matter plant on Earth.",
      "release_date": "2002-03-22"
    },
    {
      "vote_count": 0,
      "id": 305374,
      "video": false,
      "vote_average": 0,
      "title": "Circadian Rhythm",
      "popularity": 0.6,
      "poster_path": "/A5wtJMu7UDlSe5AtIF2ZHNtB9Xv.jpg",
      "original_language": "en",
      "original_title": "Circadian Rhythm",
      "genre_ids": [],
      "backdrop_path": null,
      "adult": false,
      "overview": "",
      "release_date": "2005-11-03"
    },
    {
      "vote_count": 3,
      "id": 60215,
      "video": false,
      "vote_average": 3.7,
      "title": "Darkdrive",
      "popularity": 1.024,
      "poster_path": "/f0IrDtE13MWFvbMQqAVJgVKfomd.jpg",
      "original_language": "en",
      "original_title": "Darkdrive",
      "genre_ids": [
        878,
        53
      ],
      "backdrop_path": "/Asz7nzSbjjqJ0f0e7s2pQgCiUxq.jpg",
      "adult": false,
      "overview": "Set in some distant future, one man must restore order when a mainframe system crashes in a virtual reality prison where computers control the inmates thoughts.",
      "release_date": "1996-11-01"
    },
    {
      "vote_count": 2,
      "id": 344225,
      "video": false,
      "vote_average": 7,
      "title": "Sex and the Matrix",
      "popularity": 0.901,
      "poster_path": null,
      "original_language": "en",
      "original_title": "Sex and the Matrix",
      "genre_ids": [],
      "backdrop_path": null,
      "adult": false,
      "overview": "A spoof created for the 2000 MTV Movie Awards, combining The Matrix and \"Sex in the City\".",
      "release_date": "2000-01-01"
    },
    {
      "vote_count": 6,
      "id": 27306,
      "video": false,
      "vote_average": 6.5,
      "title": "Cyber Wars",
      "popularity": 1.103,
      "poster_path": "/m8DyuXYJibitUBJqrE3CcA8CPaT.jpg",
      "original_language": "en",
      "original_title": "Cyber Wars",
      "genre_ids": [
        28,
        18,
        878,
        53
      ],
      "backdrop_path": "/754qlZv3Rm9WWnVBSS6f3jwdIbu.jpg",
      "adult": false,
      "overview": "In the near future in the Asian city-state Sintawan, everyone's identity is recorded in the vast CyberLink. The only way around this is using illegal simulated identity implants (sims). A young bounty hunter who makes her living tracking sims, finds herself the unlikely ally of a police detective who suspects the CyberLink is being perverted for an insidious and deadly purpose",
      "release_date": "2004-09-15"
    },
    {
      "vote_count": 1,
      "id": 141225,
      "video": false,
      "vote_average": 10,
      "title": "Buhera mátrix",
      "popularity": 0.6,
      "poster_path": "/ixZn1uPR3nw51plNEOpLuchWe7K.jpg",
      "original_language": "hu",
      "original_title": "Buhera mátrix",
      "genre_ids": [],
      "backdrop_path": null,
      "adult": false,
      "overview": "",
      "release_date": "2007-03-29"
    },
    {
      "vote_count": 0,
      "id": 386137,
      "video": false,
      "vote_average": 0,
      "title": "Matrix AB",
      "popularity": 0.6,
      "poster_path": "/t0IfTnOnWBrLQPoFxdtHmr4BnVS.jpg",
      "original_language": "cs",
      "original_title": "Matrix AB",
      "genre_ids": [
        99
      ],
      "backdrop_path": "/gN1MGTNHGIPTxAgyTiJkNrfvU8U.jpg",
      "adult": false,
      "overview": "",
      "release_date": "2015-10-29"
    },
    {
      "vote_count": 0,
      "id": 285435,
      "video": false,
      "vote_average": 0,
      "title": "Dot Matrix",
      "popularity": 0.6,
      "poster_path": "/u9trZUOdhWvaPwifS21NQCW0XKH.jpg",
      "original_language": "en",
      "original_title": "Dot Matrix",
      "genre_ids": [],
      "backdrop_path": null,
      "adult": false,
      "overview": "In 2012, Richard Tuohy made \"Screen Tone\" using patterns of dots printed straight to 16mm film. By doubling this principle in \"Dot Matrix\", a third, dizzying moire pattern and a deafening noise develops in the flicker (alternating black and white frames) because the dots also pass by the sound head.",
      "release_date": "2013-08-05"
    },
    {
      "vote_count": 0,
      "id": 560403,
      "video": false,
      "vote_average": 0,
      "title": "Skin Matrix",
      "popularity": 0.6,
      "poster_path": null,
      "original_language": "en",
      "original_title": "Skin Matrix",
      "genre_ids": [],
      "backdrop_path": null,
      "adult": false,
      "overview": "Emshwiller writes that the visually complex and densely textured Skin Matrix is a \"video tapestry... a layering of different manifestations of energy: electronic (light, video, computer), inorganic (dunes, rocks, mud), organic (wood, plants), human (skin, hair), individual (faces, eyes), imagination (sculpture, robot).\" His intricate electronic transformations of tactile surfaces, landscapes and human faces signify a metaphysical process that simultaneously masks and reveals; he achieves an uncanny spatial illusion of depth through layering and movement. Creating sophisticated image patterns and structures with the simple Bally Arcade computer (used for playing video games), Emshwiller weaves together the lush textures and kinetic energy of the organic and the technological.",
      "release_date": "1984-05-05"
    }
  ]
}

export default SEARCH_FILMES_RESULT;